name: document_management_system
description: "A new Flutter project."
publish_to: "none"
version: 0.1.0+1

environment:
  sdk: ^3.11.1

dependencies:
  flutter:
    sdk: flutter

  flutter_native_splash: ^2.4.7
  google_sign_in: ^7.2.0

  # Firebase core
  firebase_core: ^4.5.0
  firebase_auth: ^6.2.0
  cloud_firestore: ^6.1.3

  # State management
  get: ^4.7.3

  # File handling
  file_picker: ^10.3.10
  image_pickers: ^2.0.6
  path_provider: ^2.1.5
  path: ^1.9.1
  cunning_document_scanner: ^1.4.0
  share_plus: ^12.0.1
  flutter_doc_scanner: ^0.0.18

  # PDF

  # Signature
  signature: ^6.3.0

  # Local storage
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  flutter_secure_storage: ^10.0.0

  # Networking / utils
  uuid: ^4.5.3
  intl: ^0.20.2
  cached_network_image: ^3.4.1
  connectivity_plus: ^7.0.0
  flutter_svg: ^2.2.4
  shimmer: ^3.0.0
  lottie: ^3.3.2

  # UI
  cupertino_icons: ^1.0.8
  http: ^1.6.0
  pdfx: ^2.9.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  hive_generator: ^2.0.1
  build_runner: ^2.4.13

flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/icons/
    - assets/animations/
    - assets/fonts/

  fonts:
    - family: Inter
      fonts:
        - asset: assets/fonts/Inter-Regular.ttf
          weight: 400
        - asset: assets/fonts/Inter-Medium.ttf
          weight: 500
        - asset: assets/fonts/Inter-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/Inter-Bold.ttf
          weight: 700

    - family: Kameron
      fonts:
        - asset: assets/fonts/Kameron-Regular.ttf
          weight: 400
        - asset: assets/fonts/Kameron-Bold.ttf
          weight: 700
    - family: DancingScript
      fonts:
        - asset: assets/fonts/DancingScript-Regular.ttf
    - family: GreatVibes
      fonts:
        - asset: assets/fonts/GreatVibes-Regular.ttf
    - family: Pacifico
      fonts:
        - asset: assets/fonts/Pacifico-Regular.ttf
    - family: Satisfy
      fonts:
        - asset: assets/fonts/Satisfy-Regular.ttf

flutter_native_splash:
  color: "#3D4750"
  image: assets/images/logo_splash.png
  fullscreen: true
  android_12:
    color: "#3D4750"
    image: assets/images/logo_splash.png
    fullscreen: true
