// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCGQtmn68Qd5amk9-Ac12R8_AQ5xV2K0RE',
    appId: '1:107459462787:web:b2ce8ef4deb9d31ef53db6',
    messagingSenderId: '107459462787',
    projectId: 'document-management-syst-fdbc1',
    authDomain: 'document-management-syst-fdbc1.firebaseapp.com',
    storageBucket: 'document-management-syst-fdbc1.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAzcIISlKab65xTI-Hntvab2YE0ZrIKJpo',
    appId: '1:107459462787:android:9f53ba75ea429f7cf53db6',
    messagingSenderId: '107459462787',
    projectId: 'document-management-syst-fdbc1',
    storageBucket: 'document-management-syst-fdbc1.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCdGjfMnnUflFfG-dlQbAavywTr6j24iq8',
    appId: '1:107459462787:ios:b0973c6850d99057f53db6',
    messagingSenderId: '107459462787',
    projectId: 'document-management-syst-fdbc1',
    storageBucket: 'document-management-syst-fdbc1.firebasestorage.app',
    iosBundleId: 'com.example.documentManagementSystem',
  );
}
